inherit vendor/extra/product.mk instead of including it
This fixed this error when building for WayDroid:

error: ninja: 'vendor/lmodroid/config/waydroid.prop', needed by 'out/target/product/waydroid_x86_64/vendor/waydroid.prop', missing and no known rule to make it

Signed-off-by: hmtheboy154 <buingoc67@gmail.com>
Change-Id: I7f90f17579647425c33120010228ed19c485a791